---
- name: Prepare all Kubernetes nodes
  hosts: k8s_all
  become: yes
  vars:
    k8s_version: "1.33.5"

  tasks:
     - name: 12. Install kubelet, kubeadm, and kubectl
      ansible.builtin.apt:
        name:
          - kubelet={{ k8s_version }}-*
          - kubeadm={{ k8s_version }}-*
          - kubectl={{ k8s_version }}-*
        state: present
        update_cache: yes
        allow_downgrade: yes

    - name: 13. Hold Kubernetes packages to prevent auto-updates
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

  handlers:
    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: yes
        daemon_reload: yes
