---
- name: Setup kubectl access on control node
  hosts: k8s_master
  become: yes

  tasks:
    - name: 1. Ensure .kube directory exists on the control node
      ansible.builtin.file:
        path: "~/.kube"
        state: directory
        mode: '0755'
      delegate_to: localhost
      become: no

    - name: 2. Copy kubeconfig from master to control node
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: "~/.kube/config"
        flat: yes

    - name: 3. Install kubectl on control node
      ansible.builtin.apt:
        name: kubectl
        state: present
        update_cache: yes
      delegate_to: admin

    - name: 4. Verify kubectl access
      ansible.builtin.command: kubectl get nodes
      register: kubectl_nodes
      changed_when: false
      delegate_to: admin
      become: no

    - name: 5. Display nodes info
      ansible.builtin.debug:
        msg: "{{ kubectl_nodes.stdout_lines }}"
      delegate_to: admin
