---
- name: Setup kubectl access on ansible-control node
  hosts: k8s_master
  become: yes

  tasks:
    - name: 1. Ensure .kube directory exists on the control node
      ansible.builtin.file:
        path: "~/.kube"
        state: directory
        mode: '0755'
      delegate_to: localhost
      become: no

    - name: 2. Copy kubeconfig from master to ansible-control node
      ansible.builtin.fetch:
        src: "/etc/kubernetes/admin.conf"
        dest: "~/.kube/config"
        flat: yes

    - name: 3. Install kubectl on ansible-control node if not present
      ansible.builtin.apt:
        name: kubectl
        state: present
        update_cache: yes
      delegate_to: localhost

    - name: 4. Verify kubectl access from ansible-control node
      ansible.builtin.command: kubectl get nodes
      register: kubectl_nodes
      delegate_to: localhost
      changed_when: false
      become: no

    - name: 5. Display nodes info
      ansible.builtin.debug:
        msg: "{{ kubectl_nodes.stdout_lines }}"
      delegate_to: localhost
