---
- name: Setup kubectl on control node
  hosts: k8s_master
  become: yes

  tasks:
    - name: 1. Create temporary directory on control node
      delegate_to: localhost
      ansible.builtin.file:
        path: /tmp/kubeconfig
        state: directory
        mode: '0700'

    - name: 2. Copy kubeconfig from master to control node
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/kubeconfig/config
        flat: yes

    - name: 3. Update server IP in the fetched kubeconfig
      delegate_to: localhost
      ansible.builtin.replace:
        path: /tmp/kubeconfig/config
        regexp: '^\s*server: https://.*:6443'
        replace: "    server: https://{{ hostvars['k8s-master-01']['ansible_default_ipv4']['address'] }}:6443"

    - name: 4. Ensure .kube directory exists on control node for the current user
      delegate_to: localhost
      become: no
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0755'

    - name: 5. Move kubeconfig to its final destination and set permissions
      delegate_to: localhost
      become: no
      ansible.builtin.copy:
        remote_src: yes
        src: /tmp/kubeconfig/config
        dest: ~/.kube/config
        mode: '0600'

    - name: 6. Install kubectl on control node if needed
      delegate_to: localhost
      become: yes
      ansible.builtin.apt:
        name: kubectl
        state: present
        update_cache: yes

    - name: 7. Verify kubectl access to the cluster
      delegate_to: localhost
      become: no
      ansible.builtin.command: kubectl get nodes
      register: kubectl_nodes
      changed_when: false

    - name: 8. Display cluster nodes info
      delegate_to: localhost
      ansible.builtin.debug:
        msg: "{{ kubectl_nodes.stdout_lines }}"

    - name: 9. Clean up temporary directory on control node
      delegate_to: localhost
      ansible.builtin.file:
        path: /tmp/kubeconfig
        state: absent
