---
- name: Setup kubectl access on ansible-control node
  hosts: k8s_master
  become: yes

  tasks:
    - name: Copy kubeconfig from master to ansible-control node
      ansible.builtin.fetch:
        src: /home/admin/.kube/config
        dest: /tmp/kubeconfig
        flat: yes
      delegate_to: ansible-control

    - name: Update kubeconfig with master node IP
      ansible.builtin.replace:
        path: /tmp/kubeconfig/config
        regexp: 'server: https://127\.0\.0\.1:6443'
        replace: "server: https://{{ hostvars['k8s-master-01']['ansible_default_ipv4']['address'] }}:6443"
      delegate_to: ansible-control

    - name: Move kubeconfig to ~/.kube/config
      ansible.builtin.shell: |
        mkdir -p ~/.kube
        mv /tmp/kubeconfig/config ~/.kube/config
        chmod 600 ~/.kube/config
      delegate_to: ansible-control
    - name: Set correct permissions on kubeconfig
      ansible.builtin.file:
        path: /home/admin/.kube/config
        owner: admin
        group: admin
        mode: '0600'


    - name: Install kubectl on ansible-control node
      ansible.builtin.apt:
        name: kubectl
        state: present
        update_cache: yes
      delegate_to: ansible-control

    - name: Verify kubectl access
      ansible.builtin.shell: |
        kubectl get nodes
      register: kubectl_nodes
      delegate_to: ansible-control

    - name: Display nodes info
      ansible.builtin.debug:
        msg: "{{ kubectl_nodes.stdout }}"
