---
- name: Join Worker Nodes to Kubernetes Cluster
  hosts: k8s_all # Выполняем на всех хостах, чтобы передать факт
  become: yes
  gather_facts: no # Отключаем, т.к. факты не нужны на этом этапе

  tasks:
    # Эта задача выполнится ТОЛЬКО на мастере
    - name: 1. Read join command from the file on master
      ansible.builtin.command: cat /tmp/k8s_join_command.txt
      register: join_command_raw
      when: inventory_hostname in groups['k8s_master']

    # Эта задача сохранит команду в переменную, доступную всем хостам
    - name: 2. Store join command as a fact
      ansible.builtin.set_fact:
        k8s_join_command: "{{ hostvars[groups['k8s_master'][0]]['join_command_raw'].stdout }}"
      when: inventory_hostname in groups['k8s_master']

- name: Execute Join Command on Workers
  hosts: k8s_workers
  become: yes

  tasks:
    - name: 3. Join node to the cluster
      ansible.builtin.shell: "{{ hostvars[groups['k8s_master'][0]]['k8s_join_command'] }}"
      args:
        # Команда выполнится, только если нода еще не в кластере
        creates: /etc/kubernetes/kubelet.conf
      register: join_result

    - name: 4. Display join result
      ansible.builtin.debug:
        msg: "Node {{ inventory_hostname }} has successfully joined the cluster."
